(executable
 (name app)
 (modes js)
 (promote)
 (modules App)
 (libraries
  js_top_worker-client_fut
  code-mirror
  merlin-js.code-mirror
  merlin-js.worker.static))

(copy_files
 (mode promote)
 (files worker/merlin_worker.bc.js))

(alias
 (name all-js)
 (deps merlin_worker.bc.js app.bc.js dynamic.bc.js))
